pushing the CD stage for app deployment

diff --git a/.github/workflows/terraform-creation.yaml b/.github/workflows/terraform-creation.yaml
--- a/.github/workflows/terraform-creation.yaml
+++ b/.github/workflows/terraform-creation.yaml
@@ -141,67 +141,67 @@ jobs:
 
 #########################k8s deployment#############################
 
-  terraform-k8s-deployment:
-    name: 'Terraform-iam'
-    needs: [terraform-network-deployment, terraform-iam-deployment]
-    runs-on: ubuntu-latest
-    environment: playground
+  # terraform-k8s-deployment:
+  #   name: 'Terraform-iam'
+  #   needs: [terraform-network-deployment, terraform-iam-deployment]
+  #   runs-on: ubuntu-latest
+  #   environment: playground
     
-    env:       
-      working-directory-iam: devsecops_x_arcade_game/Terraform_configuration/env/k8s
-      TF_CLOUD_ORGANIZATION: "anshuman-test-org"
-      TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
-      TF_WORKSPACE: "arcade-workspace"
-      CONFIG_DIRECTORY: "./"
+  #   env:       
+  #     working-directory-iam: devsecops_x_arcade_game/Terraform_configuration/env/k8s
+  #     TF_CLOUD_ORGANIZATION: "anshuman-test-org"
+  #     TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
+  #     TF_WORKSPACE: "arcade-workspace"
+  #     CONFIG_DIRECTORY: "./"
 
 
-    defaults:
-      run:
-        shell: bash
+  #   defaults:
+  #     run:
+  #       shell: bash
 
-    steps:
-    - name: Set up environment variables
-      run: |
-          echo "AWS_ACCESS_KEY_ID=your-access-key-id" >> ${{ secrets.AWS_ACCESS_KEY_ID }}
-          echo "AWS_SECRET_ACCESS_KEY=your-secret-access-key" >> ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #   steps:
+  #   - name: Set up environment variables
+  #     run: |
+  #         echo "AWS_ACCESS_KEY_ID=your-access-key-id" >> ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         echo "AWS_SECRET_ACCESS_KEY=your-secret-access-key" >> ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     
-    # Repo checkout
-    - name: Checkout
-      uses: actions/checkout@v3
+  #   # Repo checkout
+  #   - name: Checkout
+  #     uses: actions/checkout@v3
 
-    # Aws IAM auth
-    - name: Configure AWS Credentials Action For GitHub Actions
-      uses: aws-actions/configure-aws-credentials@v1-node16
-      with:
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: ap-south-1
+  #   # Aws IAM auth
+  #   - name: Configure AWS Credentials Action For GitHub Actions
+  #     uses: aws-actions/configure-aws-credentials@v1-node16
+  #     with:
+  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #       aws-region: ap-south-1
 
-    # Install Terraform
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v1
-      with:
-        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+  #   # Install Terraform
+  #   - name: Setup Terraform
+  #     uses: hashicorp/setup-terraform@v1
+  #     with:
+  #       cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
-    # Terraform init
-    - name: Terraform Init
-      run: terraform init
-      working-directory: ${{ env.working-directory }}
+  #   # Terraform init
+  #   - name: Terraform Init
+  #     run: terraform init
+  #     working-directory: ${{ env.working-directory }}
 
 
-    # Terraform plan
-    - name: Terraform Plan
-      run: terraform plan -input=false
-      working-directory: ${{ env.working-directory }}
+  #   # Terraform plan
+  #   - name: Terraform Plan
+  #     run: terraform plan -input=false
+  #     working-directory: ${{ env.working-directory }}
 
-    # Exit Action on Plan Failure
-    - name: 'Terraform Plan Status'
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
-      working-directory: ${{ env.working-directory }}
+  #   # Exit Action on Plan Failure
+  #   - name: 'Terraform Plan Status'
+  #     if: steps.plan.outcome == 'failure'
+  #     run: exit 1
+  #     working-directory: ${{ env.working-directory }}
     
-    # Terraform apply
-    - name: Terraform Apply
-      # if: github.ref == 'refs/heads/"pre-master"' && github.event_name == 'push'
-      run: terraform apply -auto-approve -input=false
-      working-directory: ${{ env.working-directory }}
+  #   # Terraform apply
+  #   - name: Terraform Apply
+  #     # if: github.ref == 'refs/heads/"pre-master"' && github.event_name == 'push'
+  #     run: terraform apply -auto-approve -input=false
+  #     working-directory: ${{ env.working-directory }}
